/* eslint-disable no-unused-vars */
export enum STEPS {
  ROLE = "ROLE",
  BIO = "BIO",
  COMPENSATION = "COMPENSATION",
  SOCIALS = "SOCIALS",
  EXP = "EXP",
  EXP_DETAIL = "EXP_DETAIL",
  EXPERTISE = "EXPERTISE",
  PREFERRED_PROJECTS = "PREFERRED_PROJECTS",
}
