const mockData = {
  subCategories: {
    title: "It’s time to teach our AI what you’re looking for 👉🏽",
    subTitle: "Now, let’s get a bit more specific about those ZK interests!",
    content: [
      "Finance",
      "Sybil resistance",
      "Privacy",
      "Data & ML",
      "Authentication",
      "Identity",
      "Zk Blockchains",
      "Other",
    ],
    numMatches: "210",
  },
  "Focus On Page": {
    title: "Cool! What matters to you for this hackathon?",
    subTitle: "Let us know one or more reasons why you're here.",
    content: [
      "Winning Bounties",
      "Solving Meaningful Problems",
      "Learning new Skills",
      "Meeting new Friends",
      "Finding Investors",
      "Other",
    ],
    numMatches: "110",
  },
  "Win bounties": {
    title: "What bounties are you interested in pursuing?",
    subTitle: "Choose at least one bounty.",
    content: ["ZkSync Bounty #1($3, 000) - Account Abstraction 📦", "Other"],
    numMatches: "70",
  },
  "Solving Meaningful Problems": {
    title: "What causes do you care about?",
    subTitle: "Choose maximum 3.",
    content: [
      "Sustainable cities & communities",
      "Reduced inequalities",
      "Responsible consumptions and production",
      "Hunger",
      "Climate Action",
      "Education",
      "Life below water",
      "Clean water & sanitation",
      "Life on land",
      "Health & Wellbeing",
      "Industry, innovation & infrastructure",
      "Peace, justice & strong institutions",
      "Gender Equality",
      "Decent work & economic growth",
      "Poverty",
      "Partnership & Collaboration",
      "Affordable & clean energy",
      "Other",
    ],
    numMatches: "50",
  },
  "Learn new skills": {
    title: "What specific ZK skills are you interested in learning?",
    subTitle: "Choose at least one.",
    content: [
      "zkSync",
      "loopring",
      "starkware",
      "ZKswap",
      "Aztec",
      "Hermez",
      "Other",
    ],
    numMatches: "40",
  },
  "Meet people with complementary skills": {
    title: "What types of people are you looking for?",
    subTitle: "Choose at least one.",
    content: [
      "Frontend Developer",
      "Backend Developer",
      "Full Stack Developer",
      "Blockchain Developer",
      "Design Person",
      "Product Person",
      "Other",
    ],
    numMatches: "50",
  },
  "Engage Investors": {
    title: "What type of investors are you looking for?",
    subTitle: "Choose at least one.",
    content: [
      "Angel Investors",
      "VCs",
      "Communities",
      "DAOs",
      "Advisors",
      "Grants",
      "Other",
    ],
    numMatches: "30",
  },
  "Find a co-founder": {
    title: "How would you describe your ideal co-founder?",
    subTitle: "Choose max 3.",
    content: [
      "Technical wizz",
      "Product wizz",
      "Design wizz",
      "Bizz wizz",
      "Other",
    ],
    numMatches: "35",
  },
};

export default mockData;
